//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSoftBO.ServicioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="services.gamesoft.pucp.edu.pe", ConfigurationName="ServicioWS.GeneroWS")]
    public interface GeneroWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="services.gamesoft.pucp.edu.pe/GeneroWS/listarTodosGenerosRequest", ReplyAction="services.gamesoft.pucp.edu.pe/GeneroWS/listarTodosGenerosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GameSoftBO.ServicioWS.listarTodosGenerosResponse listarTodosGeneros(GameSoftBO.ServicioWS.listarTodosGenerosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="services.gamesoft.pucp.edu.pe/GeneroWS/listarTodosGenerosRequest", ReplyAction="services.gamesoft.pucp.edu.pe/GeneroWS/listarTodosGenerosResponse")]
        System.Threading.Tasks.Task<GameSoftBO.ServicioWS.listarTodosGenerosResponse> listarTodosGenerosAsync(GameSoftBO.ServicioWS.listarTodosGenerosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.gamesoft.pucp.edu.pe")]
    public partial class genero : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idGeneroField;
        
        private string nombreField;
        
        private videojuego[] videojuegosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idGenero {
            get {
                return this.idGeneroField;
            }
            set {
                this.idGeneroField = value;
                this.RaisePropertyChanged("idGenero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("videojuegos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public videojuego[] videojuegos {
            get {
                return this.videojuegosField;
            }
            set {
                this.videojuegosField = value;
                this.RaisePropertyChanged("videojuegos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.gamesoft.pucp.edu.pe")]
    public partial class videojuego : object, System.ComponentModel.INotifyPropertyChanged {
        
        private clasificacion clasificacionField;
        
        private bool clasificacionFieldSpecified;
        
        private double costoDesarrolloField;
        
        private System.DateTime fechaLanzamientoField;
        
        private bool fechaLanzamientoFieldSpecified;
        
        private byte[] fotoField;
        
        private genero generoField;
        
        private int idVideojuegoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public clasificacion clasificacion {
            get {
                return this.clasificacionField;
            }
            set {
                this.clasificacionField = value;
                this.RaisePropertyChanged("clasificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clasificacionSpecified {
            get {
                return this.clasificacionFieldSpecified;
            }
            set {
                this.clasificacionFieldSpecified = value;
                this.RaisePropertyChanged("clasificacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double costoDesarrollo {
            get {
                return this.costoDesarrolloField;
            }
            set {
                this.costoDesarrolloField = value;
                this.RaisePropertyChanged("costoDesarrollo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaLanzamiento {
            get {
                return this.fechaLanzamientoField;
            }
            set {
                this.fechaLanzamientoField = value;
                this.RaisePropertyChanged("fechaLanzamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaLanzamientoSpecified {
            get {
                return this.fechaLanzamientoFieldSpecified;
            }
            set {
                this.fechaLanzamientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaLanzamientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public genero genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idVideojuego {
            get {
                return this.idVideojuegoField;
            }
            set {
                this.idVideojuegoField = value;
                this.RaisePropertyChanged("idVideojuego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.gamesoft.pucp.edu.pe")]
    public enum clasificacion {
        
        /// <remarks/>
        EVERYONE,
        
        /// <remarks/>
        TEEN,
        
        /// <remarks/>
        MATURE,
        
        /// <remarks/>
        ADULTSONLY,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosGeneros", WrapperNamespace="services.gamesoft.pucp.edu.pe", IsWrapped=true)]
    public partial class listarTodosGenerosRequest {
        
        public listarTodosGenerosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosGenerosResponse", WrapperNamespace="services.gamesoft.pucp.edu.pe", IsWrapped=true)]
    public partial class listarTodosGenerosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.gamesoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GameSoftBO.ServicioWS.genero[] @return;
        
        public listarTodosGenerosResponse() {
        }
        
        public listarTodosGenerosResponse(GameSoftBO.ServicioWS.genero[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GeneroWSChannel : GameSoftBO.ServicioWS.GeneroWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeneroWSClient : System.ServiceModel.ClientBase<GameSoftBO.ServicioWS.GeneroWS>, GameSoftBO.ServicioWS.GeneroWS {
        
        public GeneroWSClient() {
        }
        
        public GeneroWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeneroWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneroWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneroWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameSoftBO.ServicioWS.listarTodosGenerosResponse GameSoftBO.ServicioWS.GeneroWS.listarTodosGeneros(GameSoftBO.ServicioWS.listarTodosGenerosRequest request) {
            return base.Channel.listarTodosGeneros(request);
        }
        
        public GameSoftBO.ServicioWS.genero[] listarTodosGeneros() {
            GameSoftBO.ServicioWS.listarTodosGenerosRequest inValue = new GameSoftBO.ServicioWS.listarTodosGenerosRequest();
            GameSoftBO.ServicioWS.listarTodosGenerosResponse retVal = ((GameSoftBO.ServicioWS.GeneroWS)(this)).listarTodosGeneros(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameSoftBO.ServicioWS.listarTodosGenerosResponse> GameSoftBO.ServicioWS.GeneroWS.listarTodosGenerosAsync(GameSoftBO.ServicioWS.listarTodosGenerosRequest request) {
            return base.Channel.listarTodosGenerosAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameSoftBO.ServicioWS.listarTodosGenerosResponse> listarTodosGenerosAsync() {
            GameSoftBO.ServicioWS.listarTodosGenerosRequest inValue = new GameSoftBO.ServicioWS.listarTodosGenerosRequest();
            return ((GameSoftBO.ServicioWS.GeneroWS)(this)).listarTodosGenerosAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="services.gamesoft.pucp.edu.pe", ConfigurationName="ServicioWS.VideojuegoWS")]
    public interface VideojuegoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="services.gamesoft.pucp.edu.pe/VideojuegoWS/insertarVideojuegoRequest", ReplyAction="services.gamesoft.pucp.edu.pe/VideojuegoWS/insertarVideojuegoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GameSoftBO.ServicioWS.insertarVideojuegoResponse insertarVideojuego(GameSoftBO.ServicioWS.insertarVideojuegoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="services.gamesoft.pucp.edu.pe/VideojuegoWS/insertarVideojuegoRequest", ReplyAction="services.gamesoft.pucp.edu.pe/VideojuegoWS/insertarVideojuegoResponse")]
        System.Threading.Tasks.Task<GameSoftBO.ServicioWS.insertarVideojuegoResponse> insertarVideojuegoAsync(GameSoftBO.ServicioWS.insertarVideojuegoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarVideojuego", WrapperNamespace="services.gamesoft.pucp.edu.pe", IsWrapped=true)]
    public partial class insertarVideojuegoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.gamesoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GameSoftBO.ServicioWS.videojuego ordenVenta;
        
        public insertarVideojuegoRequest() {
        }
        
        public insertarVideojuegoRequest(GameSoftBO.ServicioWS.videojuego ordenVenta) {
            this.ordenVenta = ordenVenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarVideojuegoResponse", WrapperNamespace="services.gamesoft.pucp.edu.pe", IsWrapped=true)]
    public partial class insertarVideojuegoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.gamesoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarVideojuegoResponse() {
        }
        
        public insertarVideojuegoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VideojuegoWSChannel : GameSoftBO.ServicioWS.VideojuegoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VideojuegoWSClient : System.ServiceModel.ClientBase<GameSoftBO.ServicioWS.VideojuegoWS>, GameSoftBO.ServicioWS.VideojuegoWS {
        
        public VideojuegoWSClient() {
        }
        
        public VideojuegoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VideojuegoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VideojuegoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VideojuegoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameSoftBO.ServicioWS.insertarVideojuegoResponse GameSoftBO.ServicioWS.VideojuegoWS.insertarVideojuego(GameSoftBO.ServicioWS.insertarVideojuegoRequest request) {
            return base.Channel.insertarVideojuego(request);
        }
        
        public int insertarVideojuego(GameSoftBO.ServicioWS.videojuego ordenVenta) {
            GameSoftBO.ServicioWS.insertarVideojuegoRequest inValue = new GameSoftBO.ServicioWS.insertarVideojuegoRequest();
            inValue.ordenVenta = ordenVenta;
            GameSoftBO.ServicioWS.insertarVideojuegoResponse retVal = ((GameSoftBO.ServicioWS.VideojuegoWS)(this)).insertarVideojuego(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameSoftBO.ServicioWS.insertarVideojuegoResponse> GameSoftBO.ServicioWS.VideojuegoWS.insertarVideojuegoAsync(GameSoftBO.ServicioWS.insertarVideojuegoRequest request) {
            return base.Channel.insertarVideojuegoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameSoftBO.ServicioWS.insertarVideojuegoResponse> insertarVideojuegoAsync(GameSoftBO.ServicioWS.videojuego ordenVenta) {
            GameSoftBO.ServicioWS.insertarVideojuegoRequest inValue = new GameSoftBO.ServicioWS.insertarVideojuegoRequest();
            inValue.ordenVenta = ordenVenta;
            return ((GameSoftBO.ServicioWS.VideojuegoWS)(this)).insertarVideojuegoAsync(inValue);
        }
    }
}
